name = "T.H.E.Y"
author = "seedl1ng"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec3641478df43d6acf939e777b740ebcb98098e1266df97abecf30e8dcbfee7a"

[versions]
forge = "0.5.14-alpha"
minecraft = "1.12.2"
