name = "THEY"
author = "seeedl1ng"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "470be6e85c7579459b11312af09007a82f19e7ec0f5d73ecc3d126ae44e31fc6"

[versions]
forge = "0.5.17-alpha"
minecraft = "1.12.2"
