#Minecraft server properties
#Wed Jun 03 23:12:43 MSK 2026
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
difficulty=2
enable-command-block=true
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
hardcore=false
level-name=world
level-seed=7551824578530800464
level-type=BIOMESOP
max-build-height=256
max-players=4
max-tick-time=60000
max-world-size=29999984
motd=\u00a74Did you hear it too?
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
resource-pack=
resource-pack-sha1=
server-ip=
server-port=25565
snooper-enabled=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
view-distance=16
white-list=false